#cloud-config
users:
  - name: hannah
    password: "$6$nzbG/B5BO/4YEyqe$fBKWA.re7VStxVf7ATCLkLIJ2zN2YB56NiJ1S/hP64qXTL.Vaqvei6Xv0/mludhviwz5ymibg.mD70BDTjvxo1"
    lock-passwd: false
    ssh_pwauth: True
    chpasswd: { expire: False }
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDBSQnrJWPNMppOgRMcyuPy7uhkbwy7cBs3KM3Znt0PN hannah@duet5"
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - git
  - software-properties-common
  - ufw
package_update: true
package_upgrade: true
runcmd:

  # Harden ssh.
  - ufw allow 227
  - ufw enable

  # Done.
  - reboot

write_files:

  # Script to install dot files.
  - path: /usr/local/bin/dot
    permissions: '0755'
    content: |
      su -c "git clone https://github.com/hbmorrison/dot.git .dot" - hannah
      su -c ".dot/update.sh" - hannah

scripts-user:
  - /usr/local/bin/dot
