#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]
timezone: Europe/London
locale: en_GB.utf8
package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - fail2ban
  - git
  - python3-systemd
  - ufw
users:
  - name: hannah
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDBSQnrJWPNMppOgRMcyuPy7uhkbwy7cBs3KM3Znt0PN
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDTncmBgMElokc+w0910ZdGGE7cmytZoAcXfO3eKNiUR
    groups: sudo, users
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
chpasswd:
  expire: false
runcmd:
  - printf "[DEFAULT]\nallowipv6 = auto\n" > /etc/fail2ban/fail2ban.local
  - printf "logtarget = SYSTEMD-JOURNAL\ndbpurgeage = 29d\n" >> /etc/fail2ban/fail2ban.local
  - printf "[DEFAULT]\nbackend = systemd\n" > /etc/fail2ban/jail.local
  - printf "banaction = nftables-multiport\n" > /etc/fail2ban/jail.local
  - printf "chain = input\n" > /etc/fail2ban/jail.local
  - printf "ignoreip = 127.0.0.1/8 ::1/128 100.64.0.0/10 fd7a:115c:a1e0::/48\n" >> /etc/fail2ban/jail.local
  - printf "bantime = 937\nfindtime = 613\nmaxretry = 3\n" >> /etc/fail2ban/jail.local
  - printf "bantime.increment = true\nbantime.factor = 2\n" >> /etc/fail2ban/jail.local
  - printf "bantime.rndtime = 311\nbantime.maxtime = 24h\n\n" >> /etc/fail2ban/jail.local
  - printf "[sshd]\nenabled = true\nmode = aggressive\n" >> /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  - systemctl restart fail2ban
  - ufw allow 22/tcp
  - ufw allow 41641/udp
  - ufw --force enable
  - sed -i -e '/^\(#\|\)PermitRootLogin/s/^.*$/PermitRootLogin without-password/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)KbdInteractiveAuthentication/s/^.*$/KbdInteractiveAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)ChallengeResponseAuthentication/s/^.*$/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^\(#\|\)AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers root hannah' /etc/ssh/sshd_config
  - systemctl restart sshd
  - su -c "git clone https://github.com/hbmorrison/dotfiles.git .dotfiles" - hannah
  - su -c ".dotfiles/bin/update.sh" - hannah
